-- Activity Bot Initial Quotes Migration
-- Runs automatically on first postgres startup via docker-entrypoint-initdb.d

CREATE TABLE IF NOT EXISTS quotes (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL CHECK (length(text) <= 500),
    author TEXT CHECK (length(author) <= 100),
    created_at TIMESTAMP DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_quotes_active ON quotes(is_active);

-- Insert all quotes from app/discord/quotes.py
INSERT INTO quotes (text, author) VALUES
('Talk is cheap. Show me the code.', 'Linus Torvalds'),
('Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', 'Martin Fowler'),
('First, solve the problem. Then, write the code.', 'John Johnson'),
('Programs must be written for people to read, and only incidentally for machines to execute.', 'Hal Abelson'),
('Simplicity is prerequisite for reliability.', 'Edsger W. Dijkstra'),
('The best code is no code at all.', 'Jeff Atwood'),
('Make it work, make it right, make it fast.', 'Kent Beck'),
('Clean code always looks like it was written by someone who cares.', 'Robert C. Martin'),
('Code is like humor. When you have to explain it, it''s bad.', 'Cory House'),
('Always code as if the guy maintaining your code is a violent psychopath who knows where you live.', 'Martin Golding'),
('Deleted code is debugged code.', 'Jeff Sickel'),
('Walking on water and developing software from a specification are easy if both are frozen.', 'Edward V. Berard'),
('Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', 'Bill Gates'),
('The most important property of a program is whether it accomplishes the intention of its user.', 'C.A.R. Hoare'),
('Debugging is twice as hard as writing the code in the first place.', 'Brian Kernighan'),
('If debugging is the process of removing bugs, then programming must be the process of putting them in.', 'Edsger W. Dijkstra'),
('Everyone knows that debugging is twice as hard as writing a program in the first place. So if you''re as clever as you can be when you write it, how will you ever debug it?', 'Brian Kernighan'),
('The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.', 'Brian Kernighan'),
('Testing leads to failure, and failure leads to understanding.', 'Burt Rutan'),
('Beware of bugs in the above code; I have only proved it correct, not tried it.', 'Donald Knuth'),
('The trouble with programmers is that you can never tell what a programmer is doing until it''s too late.', 'Seymour Cray'),
('Testing can show the presence of bugs, but not their absence.', 'Edsger W. Dijkstra'),
('A good programmer is someone who always looks both ways before crossing a one-way street.', 'Doug Linder'),
('The best thing about a boolean is even if you are wrong, you are only off by a bit.', 'Anonymous'),
('Software testing proves the existence of bugs, not their absence.', 'Edsger W. Dijkstra'),
('The best performance improvement is the transition from the nonworking state to the working state.', 'J. Osterhout'),
('It''s not a bug – it''s an undocumented feature.', 'Anonymous'),
('Without requirements or design, programming is the art of adding bugs to an empty text file.', 'Louis Srygley'),
('Don''t worry if it doesn''t work right. If everything did, you''d be out of a job.', 'Mosher''s Law of Software Engineering'),
('The best debugging tool is a good night''s sleep.', 'Anonymous'),
('Code never lies, comments sometimes do.', 'Ron Jeffries'),
('If you think your code works, you haven''t tested it enough.', 'Anonymous'),
('Premature optimization is the root of all evil.', 'Donald Knuth'),
('Simplicity is the soul of efficiency.', 'Austin Freeman'),
('Duplication is far cheaper than the wrong abstraction.', 'Sandi Metz'),
('Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.', 'Antoine de Saint-Exupéry'),
('Any code of your own that you haven''t looked at for six or more months might as well have been written by someone else.', 'Eagleson''s Law'),
('Controlling complexity is the essence of computer programming.', 'Brian Kernighan'),
('The cheapest, fastest, and most reliable components are those that aren''t there.', 'Gordon Bell'),
('One of my most productive days was throwing away 1000 lines of code.', 'Ken Thompson'),
('The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time.', 'Tom Cargill'),
('Good code is its own best documentation.', 'Steve McConnell'),
('Code that is easy to delete is easy to extend.', 'Tef'),
('Make it work, make it beautiful, make it fast.', 'Joe Armstrong'),
('Clarity is better than cleverness.', 'Eric Raymond'),
('KISS: Keep It Simple, Stupid.', 'Anonymous'),
('You aren''t gonna need it.', 'Ron Jeffries'),
('Don''t repeat yourself.', 'Andy Hunt & Dave Thomas'),
('Explicit is better than implicit.', 'The Zen of Python'),
('Code should be written to minimize the time it would take for someone else to understand it.', 'Anonymous'),
('There are only two kinds of languages: the ones people complain about and the ones nobody uses.', 'Bjarne Stroustrup'),
('I invented the term ''Object-Oriented'', and I can tell you I did not have C++ in mind.', 'Alan Kay'),
('Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.', 'Linus Torvalds'),
('Java is to JavaScript what car is to Carpet.', 'Chris Heilmann'),
('C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do it blows your whole leg off.', 'Bjarne Stroustrup'),
('There are two ways to write error-free programs; only the third one works.', 'Alan J. Perlis'),
('Python is executable pseudocode. Perl is executable line noise.', 'Bruce Eckel'),
('The best thing about Lisp is that it''s programmable.', 'Alan Kay'),
('Programming in COBOL is like kicking a dead whale down the beach.', 'Anonymous'),
('Assembly language is too high-level.', 'Anonymous Hardware Engineer'),
('Every language has an optimization operator. In C++ that operator is ''//''.', 'Anonymous'),
('The sooner you start coding, the longer the program will take.', 'Roy Carlson'),
('The problem with Git jokes is that everyone has their own version.', 'Anonymous'),
('git commit -m ''fixed stuff''', 'Every Developer at 3 AM'),
('Always commit your code at the end of the day. It makes debugging the next morning much easier.', 'Anonymous'),
('Git gets easier once you realize branches are homeomorphic endofunctors mapping submanifolds of a Hilbert space.', 'Anonymous'),
('I don''t always test my code, but when I do, I do it in production.', 'Anonymous'),
('git push --force should require a breathalyzer test.', 'Anonymous'),
('Real programmers commit directly to master.', 'Anonymous (Bad Advice)'),
('The three stages of learning git: 1) git commit 2) git commit -a 3) git push --force.', 'Anonymous'),
('There is no commit more permanent than the temporary fix.', 'Anonymous'),
('It works on my machine. ¯\_(ツ)_/¯', 'Every Developer'),
('Programming is like sex: one mistake and you''re providing support for a lifetime.', 'Michael Sinz'),
('There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.', 'Phil Karlton (Extended)'),
('99 little bugs in the code, 99 little bugs. Take one down, patch it around, 127 little bugs in the code.', 'Anonymous'),
('A user interface is like a joke. If you have to explain it, it''s not that good.', 'Martin LeBlanc'),
('In theory, theory and practice are the same. In practice, they''re not.', 'Yogi Berra'),
('Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.', 'Rick Cook'),
('Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the second law of thermodynamics; i.e., it always increases.', 'Norman Augustine'),
('Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing.', 'Dick Brandon'),
('When all else fails... reboot.', 'Anonymous'),
('Artificial Intelligence usually beats real stupidity.', 'Anonymous'),
('To err is human, to really foul things up requires a computer.', 'Paul R. Ehrlich'),
('Copy-and-paste was programmed by programmers for programmers actually.', 'Anonymous'),
('Why do programmers prefer dark mode? Because light attracts bugs.', 'Anonymous'),
('How do you comfort a JavaScript bug? You console it.', 'Anonymous'),
('A SQL query walks into a bar, walks up to two tables and asks, ''Can I join you?''', 'Anonymous'),
('There''s a band called 1023MB. They haven''t had any gigs yet.', 'Anonymous'),
('Eight bytes walk into a bar. The bartender asks, ''Can I get you anything?'' ''Yeah,'' reply the bytes. ''Make us a double.''', 'Anonymous'),
('To understand recursion, you must first understand recursion.', 'Anonymous'),
('Programming is 10% writing code and 90% understanding why it doesn''t work.', 'Anonymous'),
('Roses are red, violets are blue, unexpected ''{'' on line 32.', 'Anonymous'),
('A programmer''s wife tells him: ''While you''re at the store, get milk.'' He never comes back.', 'Anonymous'),
('The bearing of a child takes nine months, no matter how many women are assigned.', 'Fred Brooks'),
('Adding manpower to a late software project makes it later.', 'Fred Brooks'),
('Nine people can''t make a baby in a month.', 'Fred Brooks'),
('What one programmer can do in one month, two programmers can do in two months.', 'Fred Brooks'),
('Good judgment comes from experience, and experience comes from bad judgment.', 'Fred Brooks'),
('Plan to throw one away; you will, anyhow.', 'Fred Brooks'),
('Hofstadter''s Law: It always takes longer than you expect, even when you take into account Hofstadter''s Law.', 'Douglas Hofstadter'),
('The best way to get a project done faster is to start sooner.', 'Jim Highsmith'),
('Done is better than perfect.', 'Sheryl Sandberg'),
('If you don''t have time to do it right, when will you have time to do it over?', 'John Wooden');

-- ON CONFLICT DO NOTHING allows safe re-run (idempotent)
